#!/usr/bin/env bash
#install ngix and put holberton inside

sudo apt-get update -y && \
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.html
sudo service nginx restart
