#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "
frontend loadbalancer
        bind *:80
        mode http
        default_backend webservers
backend webservers
        balance roundrobin
        server 3284-web-01 35.231.236.4:80 check
        server 3284-web-02 34.74.187.179:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
