#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read this

cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
if grep "face" ~/hosts.new; then
	:
else
	echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts